name: 'Bt'

on:
  schedule:
    workflow_dispatch:
    - cron: "0 2 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'Get Tracker'
        run: bash ./bt.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TRACKER_TOKEN }}
          PUBLISH_BRANCH: BT_Merge
          publish_dir: ./tracker
