name: 'test_Bt'

on:
  workflow_dispatch:
   schedule:
     - cron: '0 21 * * *'
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Tracker'
        run: bash ./bt.sh
