name: 'test_Bt'

on:
  workflow_dispatch:
   schedule:
     - cron: '0 0 * * 0'
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Get Tracker'
        run: bash ./bt.sh
      - name: 'Upload firmware directory'
        uses: actions/upload-artifact@main
        with:
          name: tracker.txt
          path: tracker
